# Generated by Django 4.2.3 on 2023-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("marca", models.CharField(max_length=50)),
                ("preco", models.FloatField()),
                ("imagem", models.ImageField(upload_to="imagens")),
            ],
        ),
    ]
