# Generated by Django 4.2.3 on 2023-07-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Produtos",
            new_name="Produto",
        ),
    ]
