# Generated by Django 4.2.3 on 2023-07-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_rename_produtos_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="descricao",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="imagem"),
        ),
    ]
