# Generated by Django 4.2.3 on 2023-07-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0003_produto_descricao_alter_produto_imagem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Produto",
            new_name="Produtos",
        ),
    ]
